kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-cp-cloudguard-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: {{ template "cp-resource-management.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
data:
  clusterID: {{ required "CloudGaurd Cluster ID is required" .Values.clusterID | quote }}